name: Upload to Hugging Face

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  upload-to-hf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install huggingface_hub

    - name: Upload to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Directly upload without interactive login
        huggingface-cli repo create <parthamajp>/<llm_example> --type model --visibility public  # or 'private'
        huggingface-cli upload <local-folder-to-upload> --repo-id <parthamajp>/<llm_example> --token $HF_TOKEN
