name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git
        run: |
          git config --global user.name "DrParthaMajumder"
          git config --global user.email "parthamajpkk@gmail.com"

      - name: Pull with conflict handling
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git pull --rebase https://parthamajp:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/parthamajp/llm_example main || \
          (echo "Conflicts detected. Aborting rebase." && git rebase --abort && exit 1)

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://parthamajp:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/parthamajp/llm_example main


